export function getData(params) {
  const obj = [
    { 'index': '1', 'otherAppName': '中国工商银行', 'rinm': '中国工商银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '5.1.0.1.0', 'androidVersion': '5.1.0.1.0', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0001.jpg') },
    { 'index': '2', 'otherAppName': '民生银行', 'rinm': '中国民生银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '5.21', 'androidVersion': '5.21', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0002.jpg') },
    { 'index': '3', 'otherAppName': '民生信用卡', 'rinm': '中国民生银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '6.3', 'androidVersion': '6.3', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0003.jpg') },
    { 'index': '4', 'otherAppName': '徽商银行', 'rinm': '徽商银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '5.0.7', 'androidVersion': '5.0.7', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0004.jpg') },
    { 'index': '5', 'otherAppName': '京东金融', 'rinm': '京东数字科技控股有限公司', 'iosType': 'IOS', 'iosVersion': '5.3.40', 'androidVersion': '5.3.40', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0005.jpg') },
    { 'index': '6', 'otherAppName': '西安银行', 'rinm': '西安银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '6.2.5', 'androidVersion': '6.2.5', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0006.jpg') },
    { 'index': '7', 'otherAppName': '恒生中国', 'rinm': '恒生银行（中国）有限公司', 'iosType': 'IOS', 'iosVersion': '3.5.2', 'androidVersion': '3.5.2', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0007.jpg') },
    { 'index': '8', 'otherAppName': '平安口袋银行', 'rinm': '平安银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '4.28.0', 'androidVersion': '4.28.1', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0008.jpg') },
    { 'index': '9', 'otherAppName': '支付宝SDK', 'rinm': '浙江蚂蚁小微金融服务集团股份有限公司', 'iosType': 'IOS', 'iosVersion': '10.8.29-1.2.0', 'androidVersion': '10.8.29-3.7.1', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0009.jpg') },
    { 'index': '10', 'otherAppName': '广发银行', 'rinm': '广发银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '5.1.5', 'androidVersion': '5.1.5', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0010.jpg') },
    { 'index': '11', 'otherAppName': '安徽农金', 'rinm': '安徽省农村信用社联合社', 'iosType': 'IOS', 'iosVersion': '5.1.9', 'androidVersion': '', 'androidType': '', 'appIconPath': require('./assets/logo/App0011.jpg') },
    { 'index': '12', 'otherAppName': '中国银行', 'rinm': '中国银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '6.5.0', 'androidVersion': '6.5.0', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0012.jpg') },
    { 'index': '13', 'otherAppName': '九商信用卡', 'rinm': '吉林九台农村商业银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '2.1.4', 'androidVersion': '2.1.4', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0013.jpg') },
    { 'index': '14', 'otherAppName': '中国建设银行', 'rinm': '中国建设银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '4.3.3', 'androidVersion': '4.3.3', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0014.jpg') },
    { 'index': '15', 'otherAppName': '动卡空间', 'rinm': '中信银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '6.1.0', 'androidVersion': '6.1.0', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0015.jpg') },
    { 'index': '16', 'otherAppName': '中信银行', 'rinm': '中信银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '6.0.2', 'androidVersion': '6.0.2', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0016.jpg') },
    { 'index': '17', 'otherAppName': '发现精彩', 'rinm': '广发银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '4.4.0', 'androidVersion': '4.4.0', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0017.jpg') },
    { 'index': '18', 'otherAppName': '掌上生活', 'rinm': '招商银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '8.0.9', 'androidVersion': '8.0.9', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0018.jpg') },
    { 'index': '19', 'otherAppName': '招商银行', 'rinm': '招商银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '8.1.0', 'androidVersion': '8.1.0', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0019.jpg') },
    { 'index': '20', 'otherAppName': '云闪付', 'rinm': '中国银联股份有限公司', 'iosType': 'IOS', 'iosVersion': '8.0.0', 'androidVersion': '8.0.0', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0020.jpg') },
    { 'index': '21', 'otherAppName': '收款宝MAX', 'rinm': '拉卡拉支付股份有限公司', 'iosType': 'IOS', 'iosVersion': '2.3.0', 'androidVersion': '2.3.0', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0021.jpg') },
    { 'index': '22', 'otherAppName': '三峡付', 'rinm': '重庆三峡银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '2.9.26', 'androidVersion': '2.10.17', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0022.jpg') },
    { 'index': '23', 'otherAppName': '平安健康', 'rinm': '平安健康保险股份有限公司', 'iosType': 'IOS', 'iosVersion': '3.28.0', 'androidVersion': '3.27.0', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0023.jpg') },
    { 'index': '24', 'otherAppName': '微信', 'rinm': '财付通支付科技有限公司', 'iosType': 'IOS', 'iosVersion': '7.0.8', 'androidVersion': '7.0.9', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0024.jpg') },
    { 'index': '25', 'otherAppName': '广州农村商业银行移动银行', 'rinm': '广州农村商业银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '5.5.0', 'androidVersion': '5.5.5', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0025.jpg') },
    { 'index': '26', 'otherAppName': '度小满金融', 'rinm': '上海优扬新媒信息技术有限公司', 'iosType': 'IOS', 'iosVersion': '5.0.0', 'androidVersion': '5.0.1', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0026.jpg') },
    { 'index': '27', 'otherAppName': '360借条', 'rinm': '福州三六零网络小额贷款有限公司', 'iosType': 'IOS', 'iosVersion': '1.8.8', 'androidVersion': '1.7.8', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0027.jpg') },
    { 'index': '28', 'otherAppName': '宁波银行', 'rinm': '宁波银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '6.0.8', 'androidVersion': '6.1.1', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0028.jpg') },
    { 'index': '29', 'otherAppName': '兴业银行', 'rinm': '兴业银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '5.0.9', 'androidVersion': '5.0.6', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0029.jpg') },
    { 'index': '30', 'otherAppName': '东营银行', 'rinm': '东营银行股份有限公司', 'iosType': 'IOS', 'iosVersion': '4.2.2', 'androidVersion': '4.2.7', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0030.jpg') },
    { 'index': '31', 'otherAppName': '招联金融', 'rinm': '招联消费金融有限公司', 'iosType': 'IOS', 'iosVersion': '5.13', 'androidVersion': '5.13', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0031.jpg') },
    { 'index': '32', 'otherAppName': '拉卡拉', 'rinm': '广州拉卡拉网络小额贷款有限责任公司', 'iosType': 'IOS', 'iosVersion': '9.3.1', 'androidVersion': '9.3.1', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0032.jpg') },
    { 'index': '33', 'otherAppName': '榕树贷款', 'rinm': '广州数融互联网小额贷款有限公司', 'iosType': 'IOS', 'iosVersion': '3.16.0', 'androidVersion': '3.16.0', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0033.jpg') },
    { 'index': '34', 'otherAppName': '陆金所', 'rinm': '上海陆家嘴国际金融资产交易市场股份有限公司', 'iosType': 'IOS', 'iosVersion': '7.8.5', 'androidVersion': '7.8.2', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0034.jpg') },
    { 'index': '35', 'otherAppName': '东亚银行', 'rinm': '东亚银行（中国）有限公司', 'iosType': 'IOS', 'iosVersion': '3.1.31', 'androidVersion': '3.1.31', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0035.jpg') },
    { 'index': '36', 'otherAppName': '安逸花', 'rinm': '马上消费金融股份有限公司', 'iosType': 'IOS', 'iosVersion': '3.4.9', 'androidVersion': '3.4.9', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0036.jpg') },
    { 'index': '37', 'otherAppName': '陆PRO', 'rinm': '上海陆金所基金销售有限公司', 'iosType': 'IOS', 'iosVersion': '2.3.5', 'androidVersion': '2.3.1', 'androidType': 'Android', 'appIconPath': require('./assets/logo/App0037.jpg') }
  ]
  return obj
}
